name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make application-local.yml
        run: |
          cd ./src/main/resources
          echo "$YML_LOCAL" | base64 --decode > application-local.yml
        shell: bash
        env:
          YML_LOCAL: ${{ secrets.APPLICATION_LOCAL }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/unibusk_server:latest

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: docker pull latest image
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/unibusk_server:latest

      - name: stop & remove containers
        run: |
          sudo docker stop unibusk || true
          sudo docker rm unibusk || true
          
      - name: run spring boot container
        run: |
          sudo docker run -d \
            --name unibusk \
            -m 768m \
            --memory-swap=768m \
            -e JAVA_OPTS="-Xms128m -Xmx384m" \
            -p 8080:8080 \
            ${{ secrets.DOCKERHUB_USERNAME }}/unibusk_server:latest

      - name: prune unused docker data
        run: sudo docker system prune -f
