name: Blue-Green Deploy PROD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make application-prod.yml
        run: |
          cd ./src/main/resources
          echo "$YML_PROD" | base64 --decode > application-prod.yml
        shell: bash
        env:
          YML_PROD: ${{ secrets.APPLICATION_PROD }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/unibusk_server:latest

      - name: Clean up sensitive files
        if: always()
        run: |
          rm -f src/main/resources/application-prod.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - uses: actions/checkout@v4

      - name: Copy deployment files to EC2
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./deployment/prod/"
          target: ~/
          overwrite: true

      - name: Run Blue-Green Deploy Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          envs: DOCKER_USERNAME,IMAGE_NAME,IMAGE_TAG
          script: |
            cd ~/deployment/prod
            chmod +x deploy.sh
            ./deploy.sh
            docker image prune -af --filter "until=24h"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
