name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Prod File
        run: |
          echo "${{ secrets.APPLICATION_PROD }}" | base64 --decode > ./src/main/resources/application-prod.yml

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/unibusk_server .
        
      - name: Push Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/unibusk_server:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set target IP
        run: |
          STATUS=$(curl -o /dev/null -w "%{http_code}" -L -k "http://${{ secrets.UNIBUSK_SERVER_IP }}/api/env")
          echo "Current Status: $STATUS"
          
          if [ $STATUS = 200 ]; then
            CURRENT_UPSTREAM=$(curl -s -L -k "http://${{ secrets.UNIBUSK_SERVER_IP }}/api/env")
          else
            CURRENT_UPSTREAM=green
          fi
          
          echo "Current Upstream: $CURRENT_UPSTREAM"
          
          if [ $CURRENT_UPSTREAM = blue ]; then
            echo "CURRENT_UPSTREAM=blue" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
            echo "TARGET_PORT=8081" >> $GITHUB_ENV
          elif [ $CURRENT_UPSTREAM = green ]; then
            echo "CURRENT_UPSTREAM=green" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
            echo "TARGET_PORT=8080" >> $GITHUB_ENV
          else
            echo "error: Unknown upstream value"
            exit 1
          fi

      - name: Deploy New Container
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.UNIBUSK_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 30m
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/unibusk_server:latest
            
            sudo docker compose -f docker-compose-${{ env.TARGET_UPSTREAM }}.yml up -d

      - name: Check Deploy Server Health
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.UNIBUSK_SERVER_IP }}:${{ env.TARGET_PORT }}/env
          max-attempts: 5
          retry-delay: 10s

      - name: Change Nginx Upstream
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.UNIBUSK_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 

      - name: Stop Old Container
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.UNIBUSK_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop ${{ env.CURRENT_UPSTREAM }} || true
            sudo docker rm ${{ env.CURRENT_UPSTREAM }} || true
